# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js/Python Package

on:
  workflow_dispatch:  
  pull_request:
    types: [ review_requested ]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
  build-npm-package:
    needs: update-version
    if: steps.update-version.outcome == 'success' || always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
   
  build-python-package:
    needs: update-version
    runs-on: ubuntu-latest
    steps:
      - name: build release distributions
        run: |
          pip install setuptools
          python setup.py sdist

      
